services:
  code:
    build: container
    command:
      - code-server
      - --config=/config.yaml
      - --disable-telemetry
      - --disable-update-check
      - /mnt/${COMPOSE_PROJECT_NAME}
    environment:
      - CODE_GID
      - CODE_SHELL
      - CODE_UID
      - DOCKER_GID
      - HOME=/home/code
      - SHELL=${CODE_SHELL}
    group_add:
      - ${DOCKER_GID}
    hostname: code
    network_mode: host
    user: $CODE_UID:$CODE_GID
    ports:
      - 8080:8080
    volumes:
      - ..:/mnt/${COMPOSE_PROJECT_NAME}
      - ./.home/code:/home/code
      - ./config.yaml:/config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /mnt/${COMPOSE_PROJECT_NAME}
