apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: infra-ca
    files:
      - tls.crt=ca.crt
      - tls.key=ca.key
    type: kubernetes.io/tls
    options:
      disableNameSuffixHash: true
