services:
  adminer:
    depends_on:
      - postgres
    image: adminer
    ports:
      - 8081:8080
  postgres:
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    image: postgres:12
    user: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d:ro
volumes:
  postgres_data:
